"""add features

Revision ID: 016d470e02d3
Revises: 1f067146ccae
Create Date: 2026-10-10 21:37:00.706244

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "016d470e02d3"
down_revision: str | Sequence[str] | None = "1f067146ccae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "features",
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("ply", sa.Integer(), nullable=False),
        sa.Column("evaluation", sa.Integer(), nullable=True),
        sa.Column("best", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], name=op.f("fk_features_analysis_id_analyses")),
        sa.ForeignKeyConstraint(
            ["game_id", "ply"],
            ["moves.game_id", "moves.ply"],
            name=op.f("fk_features_game_id_ply_moves"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], name=op.f("fk_features_game_id_games")),
        sa.PrimaryKeyConstraint("game_id", "analysis_id", "ply", name=op.f("pk_features")),
    )
    op.drop_column("moves", "evaluation")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("moves", sa.Column("evaluation", sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table("features")
    # ### end Alembic commands ###
