"""game players, time control and played date

Revision ID: 80c3d66b225d
Revises: 1ef88918c51b
Create Date: 2026-10-10 14:48:05.361640

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "80c3d66b225d"
down_revision: str | Sequence[str] | None = "1ef88918c51b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("players", postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column("games", sa.Column("control", postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column("games", sa.Column("played", sa.DateTime(), nullable=False))
    op.create_unique_constraint(op.f("uq_games_players_played"), "games", ["players", "played"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_games_players_played"), "games", type_="unique")
    op.drop_column("games", "played")
    op.drop_column("games", "control")
    op.drop_column("games", "players")
    # ### end Alembic commands ###
