[project]
name = "blunder-client"
version = "0.1.0"
dependencies = [
    "hatchling>=1.32.0",
    "openapi-python-client>=0.29.1",
]

[build-system]
requires = ["hatchling", "openapi-python-client", "blunder-api"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/blunder"]

[tool.hatch.build.hooks.custom]
path = "hooks.py"

[tool.uv.sources]
blunder-api = { workspace = true }
